"""Write docs/DATA_DICTIONARY.md from the dbt model docs (models/marts/_marts.yml) and the
live column types in Postgres, so the dictionary cannot drift from the models.

    python -m mandipulse data-dictionary
"""

import pandas as pd
import yaml
from sqlalchemy import text

from mandipulse.config import PROJECT_ROOT
from mandipulse.db import get_engine

MARTS_YML = PROJECT_ROOT / "dbt" / "mandipulse" / "models" / "marts" / "_marts.yml"
ANALYSIS_YML = PROJECT_ROOT / "dbt" / "mandipulse" / "models" / "analysis" / "_analysis.yml"
OUT = PROJECT_ROOT / "docs" / "DATA_DICTIONARY.md"

HEADER = """# Data Dictionary

Generated by `python -m mandipulse data-dictionary` from the dbt model docs
(`dbt/mandipulse/models/marts/_marts.yml`) and the live column types in Postgres.
All prices are **Rs per quintal** (100 kg) wholesale prices.

Star schema (Postgres schema `marts`):

```
dim_date (date_key) ──┐
dim_market (market_key) ──┼── fact_daily_price (date_key, market_key, commodity_key)
dim_commodity (commodity_key) ──┘
```

Upstream layers: `raw.mandi_prices` → `staging.stg_mandi_prices` (clean, dedupe, aliases)
→ `intermediate.int_price_flags` (quality flags) → `intermediate.int_daily_prices` → marts.

Phase 3 analysis marts (`marts.mart_*`, main period only, suspect-low excluded; the same tables
including suspect-low rows are in schema `marts_incl_suspect`) follow the star schema below.
"""


def build() -> str:
    """Markdown data dictionary from the dbt yml docs and live Postgres column types."""
    spec = yaml.safe_load(MARTS_YML.read_text(encoding="utf-8"))
    analysis = yaml.safe_load(ANALYSIS_YML.read_text(encoding="utf-8"))
    # Phase 3 analysis marts (mart_*): documented where the yml has descriptions; columns
    # without one are listed with their type only (strict=False).
    for m in analysis["models"]:
        if m["name"].startswith("mart_"):
            spec["models"].append({**m, "strict": False})
    with get_engine().connect() as conn:
        types = pd.read_sql(
            text(
                "select table_name, column_name, data_type, ordinal_position "
                "from information_schema.columns where table_schema = 'marts' "
                "order by table_name, ordinal_position"
            ),
            conn,
        )
        counts = {
            m["name"]: conn.execute(text(f"select count(*) from marts.{m['name']}")).scalar_one()
            for m in spec["models"]
        }
    parts = [HEADER]
    for model in spec["models"]:
        name = model["name"]
        docs = {c["name"]: c.get("description", "") for c in model.get("columns", [])}
        cols = types[types.table_name == name]
        parts.append(f"\n## `marts.{name}`\n\n{model.get('description', '').strip()}\n")
        parts.append(f"Rows: {counts[name]}\n")
        parts.append("| Column | Type | Description |\n|---|---|---|")
        for c in cols.itertuples():
            desc = docs.get(c.column_name, "").strip().replace("|", "\|")
            parts.append(f"| `{c.column_name}` | {c.data_type} | {desc} |")
        missing = set(cols.column_name) - set(docs)
        if missing and model.get("strict", True):
            raise ValueError(f"{name}: undocumented columns {sorted(missing)}")
    return "\n".join(parts) + "\n"


def write() -> None:
    """Write docs/DATA_DICTIONARY.md."""
    OUT.write_text(build(), encoding="utf-8", newline="\n")
